CREATE TABLE IF NOT EXISTS TblCompanies (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(255) NOT NULL,
	Category VARCHAR(255) NOT NULL,
	Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
	Present BOOLEAN DEFAULT 0,
	Water BOOLEAN DEFAULT 0,
	Food BOOLEAN DEFAULT 0
);
