INSERT INTO TblCompanies (Name, Category) VALUES
('Mauritius Union Assurance - MUA', 'Gold'),
('SICOM', 'Gold'),
('VISTRA (Mauritius) Ltd', 'Gold'),
('Aspen Global Incorporated', 'Gold'),
('RAPP INDIAN OCEAN', 'Gold'),
('Aberdeen Operations Ltd', 'Gold'),
('IQ EQ', 'Gold'),
('Bolt Talent Solutions Ltd', 'Gold'),
('Axis Fiduciary Ltd', 'Gold'),
('BDO Solutions Ltd', 'Gold'),
('Business at Work (BAW)', 'Silver'),
('Spoon Consultin Limited', 'Silver'),
('Accenture (Services) Mauritius Ltd', 'Silver'),
('2Cana Solutions', 'Silver'),
('BOURBON OFFSHORE GREENMAR', 'Bronze'),
('IPCS', 'Bronze'),
('KPMG', 'Bronze'),
('Deloitte', 'Bronze'),
('TRIDENT TRUST COMPANY (MAURITIUS) LIMITED', 'Bronze'),
('Rogers Capital', 'Bronze'),
('Currimjee Jeewanjee Ltd', 'Bronze'),
('CIEL TEXTILE', 'Bronze'),
('Comfort EasyFront', 'Bronze'),
('FRCI Ltd', 'Bronze'),
('AVIPRO Co Ltd', 'Bronze'),
('DTOS Ltd', 'Bronze'),
('Checkout Support Services Ltd', 'Bronze'),
('Information Technology ELCA Ltd', 'Bronze'),
('HR CAPITALS LIMITED', 'Bronze'),
('DayForce (Mauritius) Ltd', 'Bronze'),
('HF Markets', 'Bronze'),
('ARUP (Mauritius) Ltd', 'Bronze'),
('INFOSYSTEMS AA LTD', 'Bronze')
